
all:	
	gcc -std=c11 -Wall -pedantic -Wextra -g -o auxv auxv.c
	gcc -std=c11 -Wall -pedantic -Wextra -g -o maps maps.c
	gcc -std=c11 -Wall -pedantic -Wextra  -g -o mem mem.c

change:
	gcc -std=c11 -Wall -pedantic -Wextra -DCHANGE -g -o auxv auxv.c
	gcc -std=c11 -Wall -pedantic -Wextra -DCHANGE -g -o maps maps.c
	gcc -std=c11 -Wall -pedantic -Wextra -DCHANGE  -g -o mem mem.c

